"""Hacer campos no nulos

Revision ID: 08578faf69ae
Revises: 72b8dcdaa907
Create Date: 2025-03-23 18:41:40.742716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08578faf69ae'
down_revision = '72b8dcdaa907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('paciente',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('cedula',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('compania_paciente',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('examenes',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('centro_medico',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('resultado',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('resultado',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('centro_medico',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('examenes',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('compania_paciente',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('cedula',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('paciente',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
