"""Inicialización de la base de datos con User y Auditoria

Revision ID: aa50d12b48cf
Revises: 
Create Date: 2025-03-22 17:10:52.795504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa50d12b48cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compania_paciente', sa.String(length=150), nullable=True))
        batch_op.drop_column('compania')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compania', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('compania_paciente')

    # ### end Alembic commands ###
